name: csen268
description: A Book Club sample app for HW3.
# Prevent accidental publishing to pub.dev
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  # If your Flutter uses Dart 3, change to ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management and utilities
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5

  # SVG handling (for Figma mockup overlay or vector icons)

  # Add other packages you need here
  # http: ^0.14.0
  # cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    # Put your book cover image files here
    - assets/images/
  

